#! /bin/sh

set -e

bin_dir="$(kf5-config --path exe | sed "s/.*://")"
if [ ! -d "${bin_dir}" ]; then
	mkdir -p "${bin_dir}"
fi

doc_dir="/usr/share/doc/kde-service-menu-reimage/"
if [ ! -d "${doc_dir}" ]; then
	mkdir -p "${doc_dir}"
fi

desktop_dir="$(kf5-config --path services | sed "s/.*://")ServiceMenus/"
if [ ! -d "${desktop_dir}" ]; then
	mkdir -p "${desktop_dir}"
fi
